### PR TITLE
Re-use server image for admin-tools and auto-setup builds

### PR DESCRIPTION
**Pull request by feedmeapples**
## What was changed

Re-used Server image build for the builds of Admin-Tools and Auto-Setup

## Why?

- Since the images now reuse the bins and configs from the Server image, reduces the number of variables

## Checklist

1. Closes 

2. How was this tested:

GHA run
+
locally:
```
make docker-server 
make docker-admin-tools
make docker-auto-setup
```

3. Any docs updates needed?

### CODE REVIEW

**Review by dnr — COMMENTED** [review]
Does this currently work? The latest run looks like it failed.

Honestly, I think the single Dockerfile is easier to understand and use than this combination of files and build args. With the single file you can build any of the images with a single command just by passing `--target`. You don't have to manually mess with tags across multiple commands.

Also this is still doing the `go mod download` twice (server and then admin-tools) and not sharing the go build cache between temporal-server and temporal-cassandra-tool/sql-tool. You could argue this is an acceptable cost to achieve some benefit, but there seems to be no benefit.

**Comment by feedmeapples** [comment]
> Does this currently work? The latest run looks like it failed.
> 
> Honestly, I think the single Dockerfile is easier to understand and use than this combination of files and build args. With the single file you can build any of the images with a single command just by passing `--target`. You don't have to manually mess with tags across multiple commands.
> 
> Also this is still doing the `go mod download` twice (server and then admin-tools) and not sharing the go build cache between temporal-server and temporal-cassandra-tool/sql-tool. You could argue this is an acceptable cost to achieve some benefit, but there seems to be no benefit.

I'm fine with a single dockerfile to some degree, though from personal experience i think it's useful only if you've spent some time with it. When you investigate this big dockerfile for the first time and also having the required build target seemed to create an additional learning path. With the docerfiles being split and addressing one goal at a time, imo this creates better modularity/decoupling, helps to understand the relation between the images. 
To conveniently build locally the makefile seems to be useful? In any case i'm fine to make the dockerfile a single file, let's see on practice how it goes with the image specific dockerfiles and decide if we want to have dedicated or single dockerfile

**Comment by dnr** [comment]
I'm not sure I buy it.

Take complexity:

The old thing is 81 lines. That's... not really that bad as far as Dockerfiles go?

The new thing totals 129 lines. Also not that bad, but it's more than 50% larger, and the only functional difference is it builds tctl from a separate repo.

The existing Dockerfile had 18 commits from 10 distinct authors over the past 12 months, about one every 3 weeks. So I'd argue it's not something that needs a broad understanding. If we do want to make it easier to understand, have we considered just adding a bunch more comments?

Now take usability:

With the old thing, I type `make docker-auto-setup`, and I get an image. Same for the other targets.

With the new thing, I type `make docker-auto-setup` and I get an error:
```
invalid argument "temporalio/admin-tools:" for "-t, --tag" flag: invalid reference format
```

Ok, I'm supposed to set `DOCKER_IMAGE_TAG`. So I type `make docker-auto-setup DOCKER_IMAGE_TAG=test`. I get an error:
```
Step 4/14 : FROM ${ADMIN_TOOLS_IMAGE} as admin-tools
manifest for temporalio/admin-tools:test not found: manifest unknown: manifest unknown
```

Ah, I guess I'm supposed to build admin-tools first? `make docker-admin-tools DOCKER_IMAGE_TAG=test`:
```
Step 11/19 : FROM ${SERVER_IMAGE} as server
manifest for temporalio/server:test not found: manifest unknown: manifest unknown
```

Sigh, why is there even a Makefile if I have to do manual dependency resolution?

Alright, so you put multiple build commands in each Makefile target, and say you're not supposed to run docker build yourself, you're supposed to use the Makefile. But your argument is based on ease of understanding of the dockerfile(s). If you're not supposed to use them directly, then who cares how many files they're in and whether you use `--target` or not? If you are supposed to use them directly, then I have to say they're not very usable. (And usability is more important than complexity, since there are more users than maintainers.)

Maybe I have some weird bias here. Someone else should probably weigh in. @alexshtin ?

**Comment by feedmeapples** [comment]
as discussed directly, made the `make docker-server`, `make docker-admin-tools` and `make docker-auto-setup` scripts work w/o requiring DOCKER_IMAGE_TAG and to be passed

**Review by dnr — APPROVED** [review]
Ok for now

**Pull request merged**
